### PR TITLE
Consistency between French and English version

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by ad-anssi** [comment]
Hello. I'm not sure I understand. In Rust, lifetimes are named `'a`, `'b`, `'static`, etc. so the notation `'lowercase` with the (single) single quote seems correct to me.

**Comment by DimitriPapadopoulos** [comment]
I see, you consider these are variable declarations.

If  so, there is a discrepancy between the English version:
https://github.com/ANSSI-FR/rust-guide/blob/054fb64538cec65c48bdb2f0ed556e8c38e2d25a/src/en/04_language.md#L14
and the French version:
https://github.com/ANSSI-FR/rust-guide/blob/054fb64538cec65c48bdb2f0ed556e8c38e2d25a/src/fr/04_language.md#L15

**Comment by DimitriPapadopoulos** [comment]
Actually the French version feels a little bit like an automated translation:
> La règle de base consiste à utiliser :
> [...]
> * la **`lowercase`** pour les durées de vie (_lifetimes_).

Perhaps change to:
> La règle de base consiste à utiliser :
> [...]
> * **`'lowercase`** pour les durées de vie (_lifetimes_).

**Comment by DimitriPapadopoulos** [comment]
@ad-anssi Should I create a pull request for the French version instead?

**Comment by ad-anssi** [comment]
Yes please! It would be nice

**Comment by DimitriPapadopoulos** [comment]
I've modified this pull request, I hope it's OK.

**Comment by ad-anssi** [comment]
Yes it's OK, thank you for contributing to a more "typo-free" document!

**Pull request merged**
